### ISSUE TITLE
Add `Size()` function for getting used cache size

### ISSUE THREAD

**Issue by nlachfr** [Yiling-J/theine-go#40]
Hello,

Currently, the cache has a `Len() int` function for getting the number of entries in the cache. However, when entries have different cost, it is not possible to exactly know what size of the cache is being used.

What do you think about having a `Size() int` function returning this ?

Maybe related to https://github.com/Yiling-J/theine-go/issues/26

**Comment by Yiling-J** [comment]
@nlachfr As you can see in the Len method, it simply loops through all shards and counts the items in each shard map. Adding a Size method is also straightforward; each shard map stores entries, and each entry has a cost field, so add these together you can get the Size. I think it's a small change only taking about 10 minutes. I'm currently optimizing read performance, but I can add this afterward. You can also fork and make the change yourself, and maybe submit a PR.

Once I've finished optimizing reads, my plan is to add Stats API. But I think this will likely include metrics such as hit/miss counts, rather than len/size.
