### ISSUE TITLE
Make `NotFound` public

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [Yiling-J/theine-go#46]
Hi!
It seems like the loading cache has a `NotFound` error, but it's not possible to use `errors.Is` because `NotFound` is inside `internal`. Could you make this public so that it would be possible to do `errors.Is(err, theine.ErrNotFound)` to identify when a record is not found?

**Comment by Yiling-J** [comment]
@Fire-Dragon-DoL 

The `NotFound` error is designed for internal use within the NVM cache. Specifically, it’s used in the `GetWithSecondary` method in `internal/store/go`:

```go
	if errors.As(err, &notFound) {
		return value, false, nil
	}
```

In this method, the `NotFound` error is intentionally ignored and is not propagated to the public API. The reason the method has an error parameter is due to the nature of the NVM cache, which operates on disk. This can lead to various types of errors, and simply returning a boolean would not suffice to capture these errors.

Regarding loading cahce, if the NVM cache is not enabled, any error encountered in the `Get` API will be the error returned by your loading function.

**Comment by Fire-Dragon-DoL** [comment]
> @Fire-Dragon-DoL
> 
> The `NotFound` error is designed for internal use within the NVM cache. Specifically, it’s used in the `GetWithSecondary` method in `internal/store/go`:
> 
> ```go
> 	if errors.As(err, &notFound) {
> 		return value, false, nil
> 	}
> ```
> 
> In this method, the `NotFound` error is intentionally ignored and is not propagated to the public API. The reason the method has an error parameter is due to the nature of the NVM cache, which operates on disk. This can lead to various types of errors, and simply returning a boolean would not suffice to capture these errors.
> 
> Regarding loading cahce, if the NVM cache is not enabled, any error encountered in the `Get` API will be the error returned by your loading function.

I see I misunderstood the purpose.
So in case of loadable cache, the value is always expected to be present, because fetched from the loader function in case of cache miss?

**Comment by Yiling-J** [comment]
> the value is always expected to be present, because fetched from the loader function in case of cache miss

Correct
